### ISSUE TITLE
El Gato Light Strips

### ISSUE THREAD

**Issue by derkleinemischi** [bitfocus/companion-module-elgato-keylight#13]
I recently bought the new Light Strips made by Elgato. These strips are perfect for livestreaming and/ or filming because they do not flicker on camera. It is possible to control the strips with the Streamdeck software by Elgato. Does anyone have any plans to create a module for supporting the strips with the companion app?

**Comment by estilles** [comment]
This seems to be a duplicate of #12. Closing and continuing the conversation there.
