### ISSUE TITLE
Module doesn't work with version 3

### ISSUE THREAD

**Issue by Tilltv** [bitfocus/companion-module-elgato-keylight#15]
unfortunately the module doesn't seem to work with companion version 3.

Log:
> system: ** Starting Connection from "C:\Program Files\Companion\resources\module-legacy\manifests\companion-module-elgato-keylight\index.js" **
> system: ** Connection started **
> Starting up module class: k
> Sentry disabled
> Module-host accepted registration
> error: HTTP GET Request failed (ETIMEDOUT)

Version: [3.0.0-rc2 (3.0.0-rc2+5989-stable-4d17e724)]

are you planning to update the module?
Thanks!

**Comment by isaiahfranco** [comment]
I am also waiting for this to be brought up to v3 spec. Hopefully soon!

**Comment by digitaldrummerj** [comment]
I have been using this with version 3 for a few months to turn on and off my 2 keylights and it has been working for me.
