### ISSUE TITLE
Contribution offer

### ISSUE THREAD

**Issue by estilles** [bitfocus/companion-module-elgato-keylight#4]
@JTF4 Thank you so much for the module!

I'd been working on one, but you beat me to it. I have some features I would like to contribute, including:

Cleanup
- removing unused variables declarations
- Fixing: debug declares/used but not initialized

Features
- polling light for status (power, brightness and temperature)
  - settings to allow enable/disable polling
  - settings to change polling interval
- new actions:
  - Power cycle/toggle on/off
  - Setting temperature in Kelvin (dropdown)
  - Increasing/decreasing temperature
  - increasing/decreasing brightness
- new feedbacks
  - change button color based on power status
  - change button color based on brightness
  - change button color based on temperature

I have a pull request ready for your review if you're accepting contributions.

Thanks again!

**Comment by josephdadams** [comment]
Sure! All PRs are welcome.

**Comment by estilles** [comment]
> Sure! All PRs are welcome.

Thanks! I really appreciate it. PR submitted.

**Comment by estilles** [comment]
Attached is an example of the actions and feedbacks in PR #5.

[elgato-keylight-test.zip](https://github.com/bitfocus/companion-module-elgato-keylight/files/5713484/elgato-keylight-test.zip)

**Comment by estilles** [comment]
FYI ... immediately hiding dynamic variable from the the configuration page upon unchecking polling and clicking apply depends on bitfocus/companion#1319 (implemented on bitfocus/companion#1320), which unfortunately hasn't been merged yet.

**Comment by estilles** [comment]
> Sure! All PRs are welcome.

Thank you so much for accepting and merging my PR. This is my first contribution to a Companion module. Do you (the module maintainers) submit a PR to update the module in the Companion repo or do I as a contributor?

Thanks and Merry Christmas!

**Comment by josephdadams** [comment]
We will update the module into the core Companion repo after it has gone through a manual analysis of the updated code. We will request changes with you if something needs to be updated.

**Comment by estilles** [comment]
Awesome! Thanks for the info. I really appreciate it.
